# Generated by Django 2.2.3 on 2019-07-04 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sessions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendent',
            name='position',
            field=models.CharField(default='NA', max_length=20),
        ),
    ]
