# Generated by Django 2.2.3 on 2019-07-16 03:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 16, 3, 58, 30, 806613, tzinfo=utc), verbose_name='date published'),
        ),
    ]
