# Generated by Django 2.2.1 on 2019-07-20 19:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20190720_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 20, 19, 33, 16, 571515, tzinfo=utc), verbose_name='date published'),
        ),
    ]
