# Generated by Django 2.2.1 on 2019-07-18 00:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20190716_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 18, 0, 58, 20, 4173, tzinfo=utc), verbose_name='date published'),
        ),
    ]
