# Generated by Django 2.2.3 on 2019-07-10 02:01

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20190709_1848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='lecture',
        ),
        migrations.RemoveField(
            model_name='course',
            name='student',
        ),
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course.Course'),
        ),
        migrations.AlterField(
            model_name='course',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 10, 2, 1, 40, 270329, tzinfo=utc), verbose_name='date published'),
        ),
    ]
