# Generated by Django 2.2.1 on 2019-07-20 19:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_auto_20190720_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 20, 19, 55, 31, 512319, tzinfo=utc), verbose_name='date published'),
        ),
    ]
