# Generated by Django 2.2.1 on 2019-07-22 23:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_auto_20190722_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 22, 23, 31, 39, 448802, tzinfo=utc), verbose_name='date published'),
        ),
    ]
