# Generated by Django 2.2.1 on 2019-07-10 19:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_auto_20190710_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 10, 19, 59, 49, 271847, tzinfo=utc), verbose_name='date published'),
        ),
    ]
