# Generated by Django 2.2.1 on 2019-07-22 23:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_auto_20190722_1631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_id_slug',
        ),
        migrations.AlterField(
            model_name='course',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 22, 23, 42, 14, 748101, tzinfo=utc), verbose_name='date published'),
        ),
    ]
