# Generated by Django 2.2.1 on 2019-07-10 20:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_auto_20190710_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 10, 20, 36, 15, 601161, tzinfo=utc), verbose_name='date published'),
        ),
    ]
