# Generated by Django 2.2.1 on 2019-07-10 20:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_auto_20190710_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_title_slug',
            field=models.SlugField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='student_id_slug',
            field=models.SlugField(default='student', max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 10, 20, 57, 51, 666708, tzinfo=utc), verbose_name='date published'),
        ),
    ]
