# Generated by Django 2.2.1 on 2019-07-24 04:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_auto_20190723_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 24, 4, 7, 28, 682958, tzinfo=utc), verbose_name='date published'),
        ),
    ]
