# Generated by Django 2.2.1 on 2019-07-18 02:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_auto_20190717_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 18, 2, 5, 1, 952096, tzinfo=utc), verbose_name='date published'),
        ),
    ]
