# Generated by Django 2.2.2 on 2019-07-24 16:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_auto_20190723_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 24, 16, 2, 2, 245394, tzinfo=utc), verbose_name='date published'),
        ),
    ]
