# Generated by Django 2.2.1 on 2019-07-10 21:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0014_auto_20190710_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_title_slug',
            field=models.SlugField(editable=False, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 10, 21, 35, 36, 777770, tzinfo=utc), verbose_name='date published'),
        ),
    ]
