# Generated by Django 2.2.3 on 2019-07-13 22:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0016_auto_20190710_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 13, 22, 39, 56, 837965, tzinfo=utc), verbose_name='date published'),
        ),
    ]
