# Generated by Django 2.2.1 on 2019-07-14 00:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0017_auto_20190713_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 14, 0, 32, 15, 681862, tzinfo=utc), verbose_name='date published'),
        ),
    ]
