# Generated by Django 2.2.3 on 2019-07-19 01:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0017_auto_20190717_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 19, 1, 47, 52, 355928, tzinfo=utc), verbose_name='date published'),
        ),
    ]
