# Generated by Django 2.2.3 on 2019-07-19 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0018_auto_20190718_1847'),
        ('course', '0004_auto_20190717_2029'),
    ]

    operations = [
    ]
