# Generated by Django 2.2.1 on 2019-07-14 04:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0019_auto_20190713_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 14, 4, 11, 37, 449894, tzinfo=utc), verbose_name='date published'),
        ),
    ]
