# Generated by Django 2.2.1 on 2019-07-14 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0019_auto_20190713_1755'),
        ('course', '0021_auto_20190713_2145'),
    ]

    operations = [
    ]
