# Generated by Django 2.2.3 on 2019-07-19 04:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0022_auto_20190718_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 19, 4, 24, 11, 200478, tzinfo=utc), verbose_name='date published'),
        ),
    ]
