# Generated by Django 2.2.1 on 2019-07-08 01:42

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20)),
                ('temp_id', models.CharField(default='no code', max_length=20)),
                ('position', models.CharField(default='N/A', max_length=20)),
                ('connections', models.IntegerField(default=-1)),
                ('pub_date', models.DateTimeField(default=datetime.datetime(2019, 7, 8, 1, 42, 12, 64702, tzinfo=utc), verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture_title', models.CharField(default='default', max_length=20)),
                ('pub_date', models.DateTimeField(default=datetime.datetime(2019, 7, 8, 1, 42, 11, 987480, tzinfo=utc), verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='DirEdge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(default=datetime.datetime(2019, 7, 8, 1, 42, 12, 65632, tzinfo=utc), verbose_name='date connection made')),
                ('direction_id', models.CharField(max_length=20)),
                ('attendant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lecture.Attendant')),
            ],
        ),
        migrations.AddField(
            model_name='attendant',
            name='lecture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lecture.Lecture'),
        ),
    ]
