# Generated by Django 2.2.2 on 2019-07-21 23:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import lecture.storage


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendant',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 21, 23, 40, 47, 902884, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='diredge',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 21, 23, 40, 47, 903421, tzinfo=utc), verbose_name='date connection made'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='lecture_graph',
            field=models.ImageField(null=True, storage=lecture.storage.OverwriteStorage(), upload_to='graphs'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 21, 23, 40, 47, 875637, tzinfo=utc), verbose_name='date published'),
        ),
    ]
