# Generated by Django 2.2.1 on 2019-07-18 00:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0003_auto_20190716_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='lecture_qr',
            field=models.ImageField(null=True, unique=True, upload_to='img'),
        ),
        migrations.AlterField(
            model_name='attendant',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 18, 0, 58, 19, 988168, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='diredge',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 18, 0, 58, 19, 989168, tzinfo=utc), verbose_name='date connection made'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 18, 0, 58, 19, 953194, tzinfo=utc), verbose_name='date published'),
        ),
    ]
