# Generated by Django 2.2.1 on 2019-07-18 01:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0008_auto_20190717_1833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='lecture_qr',
        ),
        migrations.AlterField(
            model_name='attendant',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 18, 1, 56, 47, 419237, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='diredge',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 18, 1, 56, 47, 420226, tzinfo=utc), verbose_name='date connection made'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 18, 1, 56, 47, 381249, tzinfo=utc), verbose_name='date published'),
        ),
    ]
