# Generated by Django 2.2.1 on 2019-07-14 04:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0021_auto_20190713_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='lecture_title_slug',
            field=models.SlugField(editable=False, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='attendant',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 14, 4, 10, 40, 79265, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='diredge',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 14, 4, 10, 40, 79265, tzinfo=utc), verbose_name='date connection made'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 14, 4, 10, 40, 39265, tzinfo=utc), verbose_name='date published'),
        ),
    ]
