# Generated by Django 2.2.3 on 2019-07-19 18:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0023_auto_20190718_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendant',
            name='attendant_key_slug',
            field=models.SlugField(editable=False, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='attendant',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 19, 18, 12, 6, 822796, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='diredge',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 19, 18, 12, 6, 823295, tzinfo=utc), verbose_name='date connection made'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 19, 18, 12, 6, 747906, tzinfo=utc), verbose_name='date published'),
        ),
    ]
