# Generated by Django 2.2.1 on 2019-07-14 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0024_auto_20190713_2145'),
        ('lecture', '0022_auto_20190713_1755'),
    ]

    operations = [
    ]
