# Generated by Django 2.2.1 on 2019-07-06 00:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0002_auto_20190705_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='session_title',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='attendant',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 6, 0, 53, 1, 361125, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='diredge',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 6, 0, 53, 1, 361125, tzinfo=utc), verbose_name='date connection made'),
        ),
    ]
