# Generated by Django 2.2.3 on 2019-07-07 22:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0004_auto_20190705_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendant',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 7, 22, 14, 10, 310763, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='diredge',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 7, 22, 14, 10, 311262, tzinfo=utc), verbose_name='date connection made'),
        ),
        migrations.AlterField(
            model_name='session',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 7, 22, 14, 10, 249318, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='session',
            name='session_title',
            field=models.CharField(default='default', max_length=20),
        ),
    ]
